### Understanding `predictions = X.dot*(theta)`

In [3]:
import numpy as np

In [5]:
X = np.array([[1,2], [3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
print(f"First row of the matrix: {X[0]}")
print(f"First element of the matrix: {X[0,0]}")

First row of the matrix: [1 2]
First element of the matrix: 1


In [9]:
theta = np.array([[2],[3]])
print(f"First row of the matrix: {theta[0]}")
print(f"First element of the matrix: {theta[0,0]}")

First row of the matrix: [2]
First element of the matrix: 2


In [13]:
#Example data
X = np.array([[1,2], [1,3],[1,4]])
theta = np.array([[2],[3]])

print(f"X shape: {X.shape}")
print(f"theta shape: {theta.shape}")

X shape: (3, 2)
theta shape: (2, 1)


### What `.dot()` does:

predictions = X.dot(theta)


for each row i in X:
    `result[i] = X[i,0]*theta[0] + X[i,1]*theta[1] + ... + X[i,n]*theta[n]`

    Or more explicitly with indexing style:

   `result[i] = X[i,0]*theta[0,0] + X[i,1]*theta[1,0]`

Which is : y_pred = w * X_i * b



In [17]:
prediction_i = X[0,0] * theta[0,0] + X[0,1]*theta[1,0]
print(prediction_i)
print()
prediction_y = X[0,0] * theta[0] + X[0,1]*theta[1]
print(prediction_y)


8

[8]


In [19]:
# Manual Calculation

prediction_0 = 1*2 + 2*3
prediction_1 = 1*2 + 3*3
prediction_2 = 1*2 + 4*3

print(f"Manual predictions: \n{prediction_0}\n{prediction_1}\n{prediction_2}\n")


#Using .dot() 
predictions_dot = X.dot(theta)
print(f"Using X.dot(theta)\n{predictions_dot}")

Manual predictions: 
8
11
14

Using X.dot(theta)
[[ 8]
 [11]
 [14]]


----------------------------------------------------------------------------------

### Different Ways to Compute Predictions

In [23]:
#Example data
X = np.array([[1,2], [1,3],[1,4]])
theta = np.array([[2],[3]])

In [26]:
# Method 1: Using .dot() (most common)
predictions_1 = X.dot(theta)
print(f"Method 1 - .dot():\n{predictions_1}")

Method 1 - .dot():
[[ 8]
 [11]
 [14]]


In [29]:
# Method 2: Using @ operator (python 3.5+, recoomended)
predictions_2 = X @ theta
print(f"Method 2 - @ operator:\n{predictions_2}\n")

Method 2 - @ operator:
[[ 8]
 [11]
 [14]]



In [35]:
#Method 3: Using np.matmul()
predictions_3 = np.matmul(X, theta)
print(f"Method 3 - np.matmul():\n{predictions_3}\n")

Method 3 - np.matmul():
[[ 8]
 [11]
 [14]]



In [37]:
#Method 4: Using np.dot() function
predictions_4 = np.dot(X, theta)
print(f"Method 4 - np.dot()\n{predictions_4}")

Method 4 - np.dot()
[[ 8]
 [11]
 [14]]


In [39]:
#Method 5: Using element-wise multiplication and sum(manual)
#This is what happens inside .dot()
#theta.T - Transpose of theta
predictions_5 = np.sum(X * theta.T, axis=1, keepdims=True)
print(f"Method 5: Element wise + sum:\n{predictions_5}")

Method 5: Element wise + sum:
[[ 8]
 [11]
 [14]]


In [41]:
#Method 6: Using einsum(Advanced, flexible)
# 'ij, jk->ik' means: sum over j dimension
prediction_6 = np.einsum('ij,jk ->ik', X, theta)
print(f"Method 6: np.einsum()\n{prediction_6}")

Method 6: np.einsum()
[[ 8]
 [11]
 [14]]


#Method 7: Using inner product (less common for matrices)
#Works only for 1D arrays, but let's see with reshaping

predictions_7 = np.array([np.inner(X[i], theta.flatten()) for i in range(X.shape[0])])
print(predictions_7)
print()
print("After reshaping")
predictions_7 = predictions_7.reshape(-1,1)
print(predictions_7)
print(f"Method 7: looping with np.inner():\n{predictions_7}\n")


In [47]:
print(f"theta:\n{theta}\n")
print(f"theta.flatten()\n{theta.flatten()}\n")

print(f"X[0]:\n{X[0]}\n")
print(f"np.inner(X[0], theta.flatten()):\n{np.inner(X[0], theta.flatten())}\n")

print(f"X.shape:\n{X.shape}\n")

theta:
[[2]
 [3]]

theta.flatten()
[2 3]

X[0]:
[1 2]

np.inner(X[0], theta.flatten()):
8

X.shape:
(3, 2)



### Lambda functions

In [75]:
square = (lambda x: x**2)(3)  #One time use
print(square) 

        #   or 

square = lambda x: x**2  #Reusuable Named Lambda 
num = 4
print(square(num))


result = (lambda x, y: x + y)(5, 3)
print(result)

9
16
8


In [49]:
#Method 8: Using broadcasting (more manual)
#theta.T broadcasts across X 
predictions_8 = (X * theta.T).sum(axis = 1, keepdims = True)
print(f"Method - Broadcasting + sum:\n{predictions_8}\n")
                            

Method - Broadcasting + sum:
[[ 8]
 [11]
 [14]]



### Performance Comparison

In [52]:
import time
import random

#Create larger dataset for timing 
np.random.seed(42)
X_large = np.random.randn(10000,10) # 10,000 examples, 10 features
theta_large = np.random.randn(10,1)

methods = {
    'X.dot(theta)' : lambda: X_large.dot(theta_large),
    'X @ theta': lambda: X_large @ theta_large,
    'np.matmul()': lambda: np.matmul(X_large, theta_large),
    'np.dot()': lambda: np.dot(X_large, theta_large),
    'einsum': lambda: np.einsum('ij,jk -> ik', X_large, theta_large),
    'broadcast & sum': lambda: (X_large * theta_large.T).sum(axis = 0, keepdims = True)
 }

for name, method in methods.items():
    start_time = time.time()
    result = method()
    end_time = time.time()

    #Verify the correctness 
    reference = X_large.dot(theta_large)
    is_correct = np.allclose(result, reference)
    print(f"{name:<20} Time: {end_time-start_time:.6f}s  Correct: {is_correct}")




X.dot(theta)         Time: 0.014917s  Correct: True
X @ theta            Time: 0.001488s  Correct: True
np.matmul()          Time: 0.000032s  Correct: True
np.dot()             Time: 0.000021s  Correct: True
einsum               Time: 0.000067s  Correct: True
broadcast & sum      Time: 0.000214s  Correct: False
